spring:
  mail:
    host: smtp.163.com
    username: qinsanfen@163.com
    password: SKBLUNHLCAGNAAMX
  rabbitmq:
    addresses: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /test
  security:
    jwt:
      key: abcdefghijk
      expire: 7
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  datasource:
    url: jdbc:mysql://localhost:32768/jwt_test
    username: root
    password: qinsanfen
    driver-class-name: com.mysql.cj.jdbc.Driver
