spring:
  mail:
    host: smtp.163.com
    username: qinsanfen@163.com
    password: SKBLUNHLCAGNAAMX
  rabbitmq:
    addresses: 192.168.0.105
    username: admin
    password: admin
    virtual-host: /test
  security:
    jwt:
      key: abcdefghijk
      expire: 7
  data:
    redis:
      host: 192.168.0.105
      port: 6379
      database: 0
  datasource:
    url: jdbc:mysql://192.168.0.105:3306/jwt_test
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
